[package]
name = "common"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt", "sync"] }
